### ISSUE TITLE
eyetracking - TO DOs

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/eCobidas#162]
- [ ] have long and short checklist
  - [ ] create an activity with all items
  - [ ] create one with only the mandatory items
  - [ ] make sure that the 2 lists are created at once
  - [ ] have one item before that will decide which of the 2 activities to present 
- [ ] check for missing items (the long list I have has less than 70 items)
- [x] use content of [paper](https://psyarxiv.com/f6qcy/), [OSF](https://osf.io/9763g/), [shinyapp](https://decisionlab.shinyapps.io/iGuidelines/) to create lists of choices for the different responses
