### ISSUE TITLE
TODO: everything but the kitchen sink

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/eCobidas#201]
- [ ] The creation of one protocol should have a list of files as input that could be csv or jsonld.
  - [ ] If CSV then it creates an activity (or several) for that table.
  - [ ] If JOSNLD then it add it directly to the protocol.
- [x] Improve CLI
- [x] Improve `make` to facilitate download, creation and validation
- [x] Add some basic validations of the spreadshseets after download
- [x] Refactor tests
- [ ] Add options to NOT write protocol files (can be useful when only a single activity is created)
- [x] Add "Others" only for select items 
- [x] In spreadsheet change `dropdown` to `select`
- ~~[ ] use a yml or json file to centralize info about a protocol (input dir, outout dir, citation ...)~~ using metatable instead
